export const SERVICE_NAMES = {
  KIWIX: 'nomad_kiwix_server',
  OLLAMA: 'nomad_ollama',
  QDRANT: 'nomad_qdrant',
  CYBERCHEF: 'nomad_cyberchef',
  FLATNOTES: 'nomad_flatnotes',
  KOLIBRI: 'nomad_kolibri',
  KOLIBRI_GEN2: 'nomad_kolibri_2',
  // Supply Depot — curated catalog (ports 8400–8499)
  STIRLING_PDF: 'nomad_stirling_pdf',
  FILEBROWSER: 'nomad_filebrowser',
  CALIBREWEB: 'nomad_calibreweb',
  IT_TOOLS: 'nomad_it_tools',
  EXCALIDRAW: 'nomad_excalidraw',
  MESHTASTIC_WEB: 'nomad_meshtastic_web',
  MESHTASTICD: 'nomad_meshtasticd',
  MESHCORE_WEB: 'nomad_meshcore_web',
  OPENHOP_REPEATER: 'nomad_openhop_repeater',
  HOMEBOX: 'nomad_homebox',
  VAULTWARDEN: 'nomad_vaultwarden',
  JELLYFIN: 'nomad_jellyfin',
}
